" Format for python
set expandtab
autocmd FileType python setlocal textwidth=79
autocmd FileType python setlocal tabstop=8
autocmd FileType python setlocal softtabstop=4
autocmd FileType python setlocal shiftwidth=4

autocmd FileType cpp setlocal textwidth=79
autocmd FileType cpp setlocal tabstop=4
autocmd FileType cpp setlocal softtabstop=2
autocmd FileType cpp setlocal shiftwidth=2
set autoindent
retab

" Syntax coloring and colorschemes in .vim/colos
syntax on
set background=dark

filetype plugin on

set visualbell

" Turn on line numbers
set number


" set every new or read *.md buffer to use the markdown filetype
autocmd BufNewFile,BufFilePre,BufRead,BufNew *.md set filetype=markdown
autocmd FileType markdown setlocal syntax=off

" Use of mouse
set mouse=a

" Tab navigation
nnoremap <C-S-tab>  :tabprevious<CR>
nnoremap <C-tab>    :tabnext<CR>
nnoremap <C-t>      :tabnew<CR>

inoremap <C-S-tab>  <Esc>:tabprevious<CR>
inoremap <C-tab>    <Esc>:tabnext<CR>
inoremap <C-t>      <Esc>:tabnew<CR>
